columnSuffix: null
handle: text
instructions: null
name: Tekst
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  createButtonLabel: null
  defaultTransform: null
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
